version: '3.4'

services:

  dbserver:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/IdentityServer/Dockerfile

  estk.api:
    image: ${DOCKER_REGISTRY-}estkapi
    build:
      context: .
      dockerfile: Services/Stock/EStk.API/Dockerfile

